# Generated by Django 4.2.3 on 2023-07-21 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name Not Available')),
                ('credits', models.CharField(default='Credits not available')),
                ('title', models.CharField(default='Title not available')),
                ('img', models.TextField(default='https://westsiderc.org/wp-content/uploads/2019/08/Image-Not-Available.png')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title not available')),
                ('media_type', models.CharField(default='Media type not available')),
                ('year', models.IntegerField()),
                ('genre', models.CharField(default='Genre not available')),
                ('duration', models.CharField(default='Duration not available')),
                ('disabilities', models.CharField(verbose_name='Disabilities not available')),
                ('themes', models.CharField(max_length=1000)),
                ('img', models.TextField(default='https://westsiderc.org/wp-content/uploads/2019/08/Image-Not-Available.png')),
                ('description', models.TextField()),
                ('cast_members', models.ManyToManyField(to='disabilityscene.cast')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Title')),
                ('reviewer_name', models.CharField(default='Anonymous')),
                ('review_text', models.TextField(default='Review Text Not Available')),
                ('date', models.CharField(default='No Date Added')),
                ('casting_score', models.IntegerField()),
                ('character_score', models.IntegerField()),
                ('originality_score', models.IntegerField()),
                ('accuracy_score', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='disabilityscene.movie')),
            ],
        ),
    ]
