# Generated by Django 4.2.3 on 2023-07-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disabilityscene', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='character_name',
            field=models.CharField(default='Character Name not available'),
        ),
    ]
