# Generated by Django 4.2.3 on 2023-07-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disabilityscene', '0002_cast_character_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='disabilities',
            field=models.CharField(default='Disabilities not available'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
