# Generated by Django 3.1 on 2023-07-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disabilityscene', '0004_alter_review_accuracy_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='character_name',
            field=models.CharField(default='Character Name not available', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cast',
            name='credits',
            field=models.CharField(default='Credits not available', max_length=1000),
        ),
        #migrations.AlterField(
            #model_name='cast',
            #name='id',
            #field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        #),
        migrations.AlterField(
            model_name='cast',
            name='img',
            field=models.TextField(default='https://westsiderc.org/wp-content/uploads/2019/08/Image-Not-Available.png', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cast',
            name='name',
            field=models.CharField(default='Name Not Available', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cast',
            name='title',
            field=models.CharField(default='Title not available', max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='disabilities',
            field=models.CharField(default='Disabilities not available', max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Genre not available', max_length=1000),
        ),
        #migrations.AlterField(
            #model_name='movie',
            #name='id',
            #field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        #),
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.TextField(default='https://westsiderc.org/wp-content/uploads/2019/08/Image-Not-Available.png', max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='media_type',
            field=models.CharField(default='Media type not available', max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='Title not available', max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.CharField(default='No Date Added', max_length=1000),
        ),
        #migrations.AlterField(
            #model_name='review',
            #name='id',
            #field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        #),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(default='Review Text Not Available', max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(default='Anonymous', max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(default='No Title', max_length=1000),
        ),
    ]
