# Generated by Django 3.1 on 2023-07-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disabilityscene', '0006_auto_20230722_2105'),
    ]

    operations = [
        #migrations.AlterField(
            #model_name='cast',
            #name='id',
            #field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        #),
        migrations.AlterField(
            model_name='cast',
            name='img',
            field=models.TextField(default='https://westsiderc.org/wp-content/uploads/2019/08/Image-Not-Available.png'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.TextField(default='https://westsiderc.org/wp-content/uploads/2019/08/Image-Not-Available.png'),
        ),
    ]
